[features]
seeds = false
skip-lint = false
[programs.devnet]
mint_nft = "BqwE3QfMqZvzXgvdqq2jnwdRrYHJyFLL8n9qF978FZr7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/emre/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
